### ISSUE TITLE
<IDK but i put this in the issues part>

### ISSUE THREAD

**Issue by MinecrafterLunar** [fnull601/QMidiCore-Quaver-Stream-Renderer#1]
Where's the .sln(i expect it to be built with VS)
Since it needs .NET framework 7.0 (
I saw ur videos running it on Android(??
Renders pretty fast
NGGYU only needs a few mins
but the preview should be built-in like Zenith
(lazy to change into chinese input method)
![qqs](https://github.com/null7323/QMidiCore-Quaver-Stream-Renderer/assets/139604008/d0e9e49c-5df0-4949-8a79-305bc5354f56)

**Comment by null7323** [comment]
很抱歉由于要高考一直没看到你的issue，而且这个程度基本已经放弃维护了，因此.sln暂时不提供。
跑在Android上的qqs是原始的版本，可以参考其他人写的分支，这个用C#编写的版本是移植的；
预览与Zenith不同是因为两者的实现不同，Zenith的预览是通过OpenGL的窗口直接实现的，而qqs的预览是软件渲染+借助ffmpeg实现的，如果要内置预览大概需要重构了（
如果你还有其他问题，你可以考虑加个qq群（中国黑乐谱协会）：1030983136，或许我可以为你解答更多问题。
